os:
  editCommand: 'floterm'

gui:
  showRandomTip: false
  showCommandLog: true
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
    activeBorderColor:
      - green
      - bold
  # showIcons: true
  showFileIcons: true
  nerdFontsVersion: "3"

git:
  overrideGpg: true # https://github.com/jesseduffield/lazygit/discussions/3948
  pagers:
    - pager: diff-so-fancy
    # - pager: delta --dark --paging=never
  commit:
    signOff: false
  ignoreWhitespaceInDiffView: false

promptToReturnFromSubprocess: false
