os:
  editCommand: 'floterm'
gui:
  showRandomTip: false
  showCommandLog: true
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git:
  overrideGpg: true # https://github.com/jesseduffield/lazygit/discussions/3948
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
promptToReturnFromSubprocess: false
